#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Themes
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#88c0d0"
bspc config presel_feedback_color	"#88c0d0"

sxhkd &
picom --config /home/zeroicey/.config/picom/picom.conf &
nitrogen --restore &
/home/zeroicey/.config/polybar/lanuch.sh
